name: hhu-auto-report

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  auto_report:
    runs-on: ubuntu-latest
    steps:
      - name: report
      - uses: actions/checkout@v2
        env:
          STU_DATA: ${{ secrets.STU_DATA }}
        run: |
          cd $GITHUB_WORKSPACE/github_action/
          chmod +x ./hhu-auto-report
          echo $STU_DATA > config.ini
          ./hhu-auto-report